### TODO

- [x] vectorize an input image matrix into a column vector
- [ ] compute the loss
- [ ] compute the accuracy
- [ ] compute the gradient of the model parameters with respect to the loss
- [ ] update the model parameters
- [ ] plot the results
- [ ] Apply the number of iterations that lead to the convergence of the algorithm



### 1. Load training/validation image dataset

In [32]:
import torch
import torchvision
import torchvision.transforms as transforms

# define vectorize transformer
class VectorizeTransform:
    def __call__(self, img):
        return torch.reshape(img, (-1, ))

# compose image transformer
transform = transforms.Compose([
    transforms.Grayscale(),
    transforms.ToTensor(),
    VectorizeTransform()    # for vectorizing input image
])

# load training dataset
train_data_path = './data/horse-or-human/train'
train_dataset = torchvision.datasets.ImageFolder(root=train_data_path, transform=transform)
train_loader = torch.utils.data.DataLoader(
    train_dataset,
    batch_size=8,
    shuffle=True,
    num_workers=4
)

# load validation dataset
valid_data_path = './data/horse-or-human/validation'
valid_dataset = torchvision.datasets.ImageFolder(root=valid_data_path, transform=transform)
valid_loader = torch.utils.data.DataLoader(
    valid_dataset,
    batch_size=8,
    shuffle=True,
    num_workers=4
)


In [33]:
for batch_idx, (images, labels) in enumerate(train_loader):
    print(images.shape)
    print(labels)







torch.Size([8, 10000])
tensor([1, 1, 0, 0, 1, 0, 0, 0])
torch.Size([8, 10000])
tensor([0, 0, 1, 1, 0, 1, 1, 0])
torch.Size([8, 10000])
tensor([1, 1, 1, 1, 1, 0, 1, 0])
torch.Size([8, 10000])
tensor([1, 1, 1, 0, 0, 0, 0, 0])
torch.Size([8, 10000])
tensor([1, 0, 0, 0, 0, 1, 0, 1])
torch.Size([8, 10000])
tensor([1, 1, 1, 1, 0, 0, 0, 1])
torch.Size([8, 10000])
tensor([1, 1, 0, 1, 0, 0, 1, 1])
torch.Size([8, 10000])
tensor([0, 1, 0, 0, 0, 1, 0, 0])
torch.Size([8, 10000])
tensor([0, 1, 1, 0, 1, 0, 0, 1])
torch.Size([8, 10000])
tensor([0, 1, 1, 0, 0, 1, 0, 1])
torch.Size([8, 10000])
tensor([1, 1, 1, 1, 0, 0, 0, 1])
torch.Size([8, 10000])
tensor([1, 1, 1, 0, 1, 0, 1, 1])
torch.Size([8, 10000])
tensor([1, 1, 1, 1, 0, 1, 0, 1])
torch.Size([8, 10000])
tensor([1, 1, 1, 1, 0, 0, 1, 1])
torch.Size([8, 10000])
tensor([0, 1, 1, 1, 0, 0, 0, 1])
torch.Size([8, 10000])
tensor([0, 0, 0, 0, 1, 0, 0, 0])
torch.Size([8, 10000])
tensor([1, 0, 0, 1, 0, 0, 1, 0])
torch.Size([8, 10000])
tensor([0, 1, 1, 1, 1, 0,