In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-2.3969e+14,  4.5842e-41,  2.9287e-43],
        [ 0.0000e+00,  2.7746e-43,  0.0000e+00],
        [-2.3998e+14,  4.5842e-41,  0.0000e+00],
        [-8.5899e+09,  0.0000e+00, -8.5899e+09],
        [ 7.0065e-45,  0.0000e+00,  0.0000e+00]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7304, 0.3507, 0.4491],
        [0.1387, 0.0805, 0.2489],
        [0.2473, 0.6633, 0.3991],
        [0.4046, 0.9447, 0.2544],
        [0.4197, 0.8067, 0.7977]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-8.1210e-01, -8.1889e-01,  1.2320e-01],
        [ 5.5364e-01,  3.5028e-01, -5.6381e-01],
        [ 3.5388e-01, -1.5940e-01,  1.3818e+00],
        [ 1.2031e-03, -1.7688e-01, -1.3837e+00],
        [-5.9924e-01, -1.2157e-01, -8.0180e-01]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.5846,  0.1536,  0.3861],
        [ 0.8871,  1.2168, -0.1170],
        [ 1.3126,  0.7312,  2.2054],
        [ 0.7006, -0.0706, -1.3403],
        [ 0.0074,  0.3582, -0.7103]])


In [10]:
print(torch.add(x, y))

tensor([[-0.5846,  0.1536,  0.3861],
        [ 0.8871,  1.2168, -0.1170],
        [ 1.3126,  0.7312,  2.2054],
        [ 0.7006, -0.0706, -1.3403],
        [ 0.0074,  0.3582, -0.7103]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.5846,  0.1536,  0.3861],
        [ 0.8871,  1.2168, -0.1170],
        [ 1.3126,  0.7312,  2.2054],
        [ 0.7006, -0.0706, -1.3403],
        [ 0.0074,  0.3582, -0.7103]])


In [12]:
y.add_(x)
print(y)

tensor([[-0.5846,  0.1536,  0.3861],
        [ 0.8871,  1.2168, -0.1170],
        [ 1.3126,  0.7312,  2.2054],
        [ 0.7006, -0.0706, -1.3403],
        [ 0.0074,  0.3582, -0.7103]])


In [13]:
print(x[:, 1])

tensor([-0.8189,  0.3503, -0.1594, -0.1769, -0.1216])


In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print (x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0090])
0.008972345851361752


In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
